import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, CssBaseline } from "@mui/material";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />

        <Container>
          <ToastContainer />
          {children}
        </Container>
      </body>
    </html>
  );
}
